apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
spec:
  containers:
    - name: stremio-zamunda
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - containerPort: {{ .Values.containerPort }}
      env:
        - name: OMDB_API_KEY
          value: "3715ba65"
        - name: laff
          value: "ваш-замунда-потребител"
        - name: ZAMUNDA_PASSWORD
          value: "3825915009"
        - name: BG_AUDIO
