apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
spec:
  containers:
    - name: stremio-zamunda
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - containerPort: {{ .Values.containerPort }}
env:
  - name: OMDB_API_KEY
    value: "{{ .Values.env.omdbApiKey }}"
  - name: ZAMUNDA_USERNAME
    value: "{{ .Values.env.zamundaUser }}"
  - name: ZAMUNDA_PASSWORD
    value: "{{ .Values.env.zamundaPass }}"
  - name: BG_AUDIO
    value: "{{ .Values.env.bgAudio }}"
